[package]
name = "theremotion"
version = "1.3.1-dev"
authors = ["Pierre Lulé <pierre@lule.fr>"]
edition = "2021"
rust-version = "1.60"
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/plule/theremotion"
homepage = "https://plule.github.io/theremotion"
documentation = "https://plule.github.io/theremotion"
description = "Theremotion is a synthesizer inspired by the Theremin controlled by a Leap Motion"
links = "LeapC"

[features]
default = ["default-boxed", "leap"]
leap = ["leaprs"]
default-boxed = []

[dependencies]
egui = "0.22"
eframe = { version = "0.22" }
tracing-subscriber = "0.3"
cpal = "0.15"
# temporary fork: https://github.com/Frando/rust-faust/pull/19
faust-types = { git = "https://github.com/plule/rust-faust", branch = "main" }
faust-state = { git = "https://github.com/plule/rust-faust", branch = "main" }
leaprs = { version = "0.1", default-features = false, optional = true }
crossbeam-channel = "0.5"
nalgebra = "0.32"
staff = { version = "0.11", default-features = false, features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
default-boxed = "0.2"
strum = { version = "0.25", features = ["strum_macros", "derive"] }
directories = "5.0.1"
anyhow = "1"
log = "0.4"
itertools = "0.11"
lazy_static = "1.4.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.51.1", features = [
    "Win32_System_Threading",
    "Win32_Foundation",
] }

[dev-dependencies]
rstest = "0.18.2"

[build-dependencies]
faust-build = { git = "https://github.com/plule/rust-faust", branch = "main" }
image = "0.24"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
ProductName = "Theremotion"
