[package]
name = "theremotion"
version = "1.3.1-dev"
authors = ["Pierre Lulé <pierre@lule.fr>"]
edition = "2021"
rust-version = "1.60"
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/plule/theremotion"
homepage = "https://plule.github.io/theremotion"
documentation = "https://plule.github.io/theremotion"
description = "Theremotion is a synthesizer inspired by the Theremin controlled by a Leap Motion"

[features]
default = ["default-boxed", "leap"]
leap = ["leaprs"]
default-boxed = []

[dependencies]
egui = "0.20.1"
eframe = { version = "0.20.1" }
tracing-subscriber = "0.3"
cpal = "0.14"
faust-types = { git = "https://github.com/Frando/rust-faust", branch="main" }
faust-state = { git = "https://github.com/Frando/rust-faust", branch="main" }
leaprs = { version = "0.1", default-features = false, optional = true }
crossbeam-channel = "0.5"
nalgebra = "0.32"
staff = { version = "0.9.0", default-features = false, features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
default-boxed = "0.2"
strum = { version = "0.24", features = ["strum_macros", "derive"] }
windows = { version = "0.43.0", features = ["Win32_System_Threading", "Win32_Foundation"] }
directories = "4"
anyhow = "1"
log = "0.4"
itertools = "0.10"
lazy_static = "1.4.0"

[dev-dependencies]
rstest = "0.16"

[build-dependencies]
faust-build = { git = "https://github.com/Frando/rust-faust", branch="main" }
image = "0.24"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
ProductName = "Theremotion"
