[package]
name = "theremotion"
version = "0.1.13-dev"
authors = ["Pierre Lulé <pierre@lule.fr>"]
edition = "2021"
rust-version = "1.60"

[features]
default = ["gemini", "default-boxed"]
gemini = ["leaprs/gemini"]
default-boxed = []

[dependencies]
egui = "0.19.0"
eframe = { version = "0.19.0" }
tracing-subscriber = "0.3"
cpal = "0.14.0"
faust-types = { git = "https://github.com/plule/rust-faust", branch="default_boxed" }
faust-state = { git = "https://github.com/plule/rust-faust", branch="default_boxed" }
leaprs = { version = "0.1.0", default-features = false }
crossbeam-channel = "0.5.6"
nalgebra = "0.31.3"
staff = { git = "https://github.com/matthunz/staff", branch="main", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4", features = ["derive"] }
default-boxed = "0.2.0"
strum = { version = "0.24.1", features = ["strum_macros", "derive"] }

[dev-dependencies]
rstest = "0.15.0"

[build-dependencies]
faust-build = { git = "https://github.com/plule/rust-faust", branch="default_boxed" }
