name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always
  WIX_EXTRA_ARGS: ""

jobs:
  tests:
    strategy:
      matrix:
        runs-on: [windows-latest, ubuntu-latest]
    name: tests
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        if: ${{ matrix.runs-on == 'ubuntu-latest' }}
        run: sudo apt-get install -y libasound2-dev
      - name: Style
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Tests
        run: cargo test --no-default-features --features default-boxed
  build:
    strategy:
      matrix:
        include:
          - name: windows
            runs-on: windows-latest
            leapsdk-lib-path: LeapSDK/lib/x64
            leapsdk-ref: windows-gemini
            exe-name: theremotion.exe
            wix: true
            portable-type: zip
            portable-name: theremotion-windows.zip
          - name: linux
            runs-on: ubuntu-latest
            leapsdk-lib-path: ultraleap-hand-tracking-service
            leapsdk-ref: linux-gemini
            exe-name: theremotion
            portable-type: tar
            portable-name: theremotion-linux.tar.gz
    name: build
    if: eq(${{ github.repository }}, "plule/theremotion") # no secrets in clones
    runs-on: ${{ matrix.runs-on }}
    env:
      LEAPSDK_LIB_PATH: leap-sdk-redist/${{ matrix.leapsdk-lib-path }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        ref: ${{ matrix.leapsdk-ref }}
        repository: plule/leap-sdk-redist
        token: ${{ secrets.LEAP_SDK_REDIST_PAT }}
        path: leap-sdk-redist
    - uses: Swatinem/rust-cache@v2
    - name: Install dependencies
      if: ${{ matrix.runs-on == 'ubuntu-latest' }}
      run: sudo apt-get install -y libasound2-dev
    - name: Install cargo wix
      run: cargo install cargo-wix
      if: ${{ matrix.wix }}
    - name: Build
      run: cargo build --release
    - name: Outside of a release, override the version
      run: echo "WIX_EXTRA_ARGS=--install-version 0.0.0" >> $env:GITHUB_ENV
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }} && ${{ matrix.wix }}
    - name: Make installer
      run: cargo wix --nocapture --output . ${{ env.WIX_EXTRA_ARGS }}
      if: ${{ matrix.wix }}
    - name: Prepare artifacts
      run: |
        mkdir -p theremotion-${{ matrix.name }}
        cp leap-sdk-redist/${{ matrix.leapsdk-lib-path }}/*LeapC.* theremotion-${{ matrix.name }}
        cp target/release/${{ matrix.exe-name }} theremotion-${{ matrix.name }}
    - name: Archive portable version
      uses: thedoctor0/zip-release@main
      with:
        type: ${{ matrix.portable-type }}
        filename: ${{ matrix.portable-name }}
        path: theremotion-${{ matrix.name }}
    - name: Store portable version and installer
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          ${{ matrix.portable-name }}
          theremotion-*.msi
  release:
    needs:
      - build
      - tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v3
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        artifacts: dist/*
        draft: true

  dependabot:
    name: 'Dependabot automerge'
    needs:
      - build
      - tests
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} # Detect that the PR author is dependabot
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.9.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
